/**
 * Реестр всех доступных фотографий в папке photo/
 * Админ выбирает фото из этого списка при добавлении точки.
 */
var AVAILABLE_PHOTOS = [
    // Без камер (слепые зоны)
    { file: "photo/без камер/1 (1).jpeg", label_ru: "Без камер #1", label_kz: "Камерасыз #1", category: "blind-spots" },
    { file: "photo/без камер/1 (2).jpeg", label_ru: "Без камер #2", label_kz: "Камерасыз #2", category: "blind-spots" },
    { file: "photo/без камер/1 (3).jpeg", label_ru: "Без камер #3", label_kz: "Камерасыз #3", category: "blind-spots" },
    { file: "photo/без камер/1 (4).jpeg", label_ru: "Без камер #4", label_kz: "Камерасыз #4", category: "blind-spots" },
    { file: "photo/без камер/1 (5).jpeg", label_ru: "Без камер #5", label_kz: "Камерасыз #5", category: "blind-spots" },
    { file: "photo/без камер/1 (6).jpeg", label_ru: "Без камер #6", label_kz: "Камерасыз #6", category: "blind-spots" },
    { file: "photo/без камер/1 (7).jpeg", label_ru: "Без камер #7", label_kz: "Камерасыз #7", category: "blind-spots" },
    { file: "photo/без камер/1 (8).jpeg", label_ru: "Без камер #8", label_kz: "Камерасыз #8", category: "blind-spots" },
    { file: "photo/без камер/1 (9).jpeg", label_ru: "Без камер #9", label_kz: "Камерасыз #9", category: "blind-spots" },
    { file: "photo/без камер/1 (10).jpeg", label_ru: "Без камер #10", label_kz: "Камерасыз #10", category: "blind-spots" },
    { file: "photo/без камер/1 (11).jpeg", label_ru: "Без камер #11", label_kz: "Камерасыз #11", category: "blind-spots" },
    { file: "photo/без камер/1 (12).jpeg", label_ru: "Без камер #12", label_kz: "Камерасыз #12", category: "blind-spots" },
    { file: "photo/без камер/1 (13).jpeg", label_ru: "Без камер #13", label_kz: "Камерасыз #13", category: "blind-spots" },
    { file: "photo/без камер/1 (14).jpeg", label_ru: "Без камер #14", label_kz: "Камерасыз #14", category: "blind-spots" },
    { file: "photo/без камер/1 (15).jpeg", label_ru: "Без камер #15", label_kz: "Камерасыз #15", category: "blind-spots" },
    { file: "photo/без камер/1 (16).jpeg", label_ru: "Без камер #16", label_kz: "Камерасыз #16", category: "blind-spots" },
    { file: "photo/без камер/1 (17).jpeg", label_ru: "Без камер #17", label_kz: "Камерасыз #17", category: "blind-spots" },
    { file: "photo/без камер/1 (18).jpeg", label_ru: "Без камер #18", label_kz: "Камерасыз #18", category: "blind-spots" },
    { file: "photo/без камер/1 (19).jpeg", label_ru: "Без камер #19", label_kz: "Камерасыз #19", category: "blind-spots" },
    { file: "photo/без камер/1 (20).jpeg", label_ru: "Без камер #20", label_kz: "Камерасыз #20", category: "blind-spots" },
    { file: "photo/без камер/1 (21).jpeg", label_ru: "Без камер #21", label_kz: "Камерасыз #21", category: "blind-spots" },
    { file: "photo/без камер/1 (22).jpeg", label_ru: "Без камер #22", label_kz: "Камерасыз #22", category: "blind-spots" },
    { file: "photo/без камер/1 (23).jpeg", label_ru: "Без камер #23", label_kz: "Камерасыз #23", category: "blind-spots" },
    { file: "photo/без камер/1 (24).jpeg", label_ru: "Без камер #24", label_kz: "Камерасыз #24", category: "blind-spots" },
    { file: "photo/без камер/1 (25).jpeg", label_ru: "Без камер #25", label_kz: "Камерасыз #25", category: "blind-spots" },
    { file: "photo/без камер/1 (26).jpeg", label_ru: "Без камер #26", label_kz: "Камерасыз #26", category: "blind-spots" },
    { file: "photo/без камер/1 (27).jpeg", label_ru: "Без камер #27", label_kz: "Камерасыз #27", category: "blind-spots" },
    { file: "photo/без камер/1 (28).jpeg", label_ru: "Без камер #28", label_kz: "Камерасыз #28", category: "blind-spots" },
    { file: "photo/без камер/1 (29).jpeg", label_ru: "Без камер #29", label_kz: "Камерасыз #29", category: "blind-spots" },
    { file: "photo/без камер/1 (30).jpeg", label_ru: "Без камер #30", label_kz: "Камерасыз #30", category: "blind-spots" },
    { file: "photo/без камер/1 (31).jpeg", label_ru: "Без камер #31", label_kz: "Камерасыз #31", category: "blind-spots" },
    { file: "photo/без камер/1 (32).jpeg", label_ru: "Без камер #32", label_kz: "Камерасыз #32", category: "blind-spots" },
    { file: "photo/без камер/1 (33).jpeg", label_ru: "Без камер #33", label_kz: "Камерасыз #33", category: "blind-spots" },
    { file: "photo/без камер/1 (34).jpeg", label_ru: "Без камер #34", label_kz: "Камерасыз #34", category: "blind-spots" },
    { file: "photo/без камер/1 (35).jpeg", label_ru: "Без камер #35", label_kz: "Камерасыз #35", category: "blind-spots" },
    { file: "photo/без камер/1 (36).jpeg", label_ru: "Без камер #36", label_kz: "Камерасыз #36", category: "blind-spots" },
    { file: "photo/без камер/1 (37).jpeg", label_ru: "Без камер #37", label_kz: "Камерасыз #37", category: "blind-spots" },
    { file: "photo/без камер/1 (38).jpeg", label_ru: "Без камер #38", label_kz: "Камерасыз #38", category: "blind-spots" },
    { file: "photo/без камер/1 (39).jpeg", label_ru: "Без камер #39", label_kz: "Камерасыз #39", category: "blind-spots" },
    { file: "photo/без камер/1 (40).jpeg", label_ru: "Без камер #40", label_kz: "Камерасыз #40", category: "blind-spots" },
    { file: "photo/без камер/1 (41).jpeg", label_ru: "Без камер #41", label_kz: "Камерасыз #41", category: "blind-spots" },
    { file: "photo/без камер/1 (42).jpeg", label_ru: "Без камер #42", label_kz: "Камерасыз #42", category: "blind-spots" },
    { file: "photo/без камер/1 (43).jpeg", label_ru: "Без камер #43", label_kz: "Камерасыз #43", category: "blind-spots" },
    { file: "photo/без камер/1 (44).jpeg", label_ru: "Без камер #44", label_kz: "Камерасыз #44", category: "blind-spots" },
    { file: "photo/без камер/1 (45).jpeg", label_ru: "Без камер #45", label_kz: "Камерасыз #45", category: "blind-spots" },
    { file: "photo/без камер/1 (46).jpeg", label_ru: "Без камер #46", label_kz: "Камерасыз #46", category: "blind-spots" },
    { file: "photo/без камер/1 (47).jpeg", label_ru: "Без камер #47", label_kz: "Камерасыз #47", category: "blind-spots" },
    { file: "photo/без камер/1 (48).jpeg", label_ru: "Без камер #48", label_kz: "Камерасыз #48", category: "blind-spots" },
    { file: "photo/без камер/1 (49).jpeg", label_ru: "Без камер #49", label_kz: "Камерасыз #49", category: "blind-spots" },
    { file: "photo/без камер/1 (50).jpeg", label_ru: "Без камер #50", label_kz: "Камерасыз #50", category: "blind-spots" },
    { file: "photo/без камер/2 (1).jpeg", label_ru: "Без камер #51", label_kz: "Камерасыз #51", category: "blind-spots" },
    { file: "photo/без камер/2 (2).jpeg", label_ru: "Без камер #52", label_kz: "Камерасыз #52", category: "blind-spots" },
    { file: "photo/без камер/2 (3).jpeg", label_ru: "Без камер #53", label_kz: "Камерасыз #53", category: "blind-spots" },
    { file: "photo/без камер/2 (4).jpeg", label_ru: "Без камер #54", label_kz: "Камерасыз #54", category: "blind-spots" },
    { file: "photo/без камер/2 (5).jpeg", label_ru: "Без камер #55", label_kz: "Камерасыз #55", category: "blind-spots" },
    { file: "photo/без камер/2 (6).jpeg", label_ru: "Без камер #56", label_kz: "Камерасыз #56", category: "blind-spots" },
    { file: "photo/без камер/2 (7).jpeg", label_ru: "Без камер #57", label_kz: "Камерасыз #57", category: "blind-spots" },
    { file: "photo/без камер/2 (8).jpeg", label_ru: "Без камер #58", label_kz: "Камерасыз #58", category: "blind-spots" },
    { file: "photo/без камер/2 (9).jpeg", label_ru: "Без камер #59", label_kz: "Камерасыз #59", category: "blind-spots" },
    { file: "photo/без камер/2 (10).jpeg", label_ru: "Без камер #60", label_kz: "Камерасыз #60", category: "blind-spots" },
    { file: "photo/без камер/2 (11).jpeg", label_ru: "Без камер #61", label_kz: "Камерасыз #61", category: "blind-spots" },
    { file: "photo/без камер/2 (12).jpeg", label_ru: "Без камер #62", label_kz: "Камерасыз #62", category: "blind-spots" },
    { file: "photo/без камер/2 (13).jpeg", label_ru: "Без камер #63", label_kz: "Камерасыз #63", category: "blind-spots" },
    { file: "photo/без камер/2 (14).jpeg", label_ru: "Без камер #64", label_kz: "Камерасыз #64", category: "blind-spots" },
    { file: "photo/без камер/2 (15).jpeg", label_ru: "Без камер #65", label_kz: "Камерасыз #65", category: "blind-spots" },
    { file: "photo/без камер/2 (16).jpeg", label_ru: "Без камер #66", label_kz: "Камерасыз #66", category: "blind-spots" },
    { file: "photo/без камер/2 (17).jpeg", label_ru: "Без камер #67", label_kz: "Камерасыз #67", category: "blind-spots" },
    { file: "photo/без камер/2 (18).jpeg", label_ru: "Без камер #68", label_kz: "Камерасыз #68", category: "blind-spots" },
    { file: "photo/без камер/2 (19).jpeg", label_ru: "Без камер #69", label_kz: "Камерасыз #69", category: "blind-spots" },
    { file: "photo/без камер/2 (20).jpeg", label_ru: "Без камер #70", label_kz: "Камерасыз #70", category: "blind-spots" },
    { file: "photo/без камер/2 (21).jpeg", label_ru: "Без камер #71", label_kz: "Камерасыз #71", category: "blind-spots" },
    { file: "photo/без камер/2 (22).jpeg", label_ru: "Без камер #72", label_kz: "Камерасыз #72", category: "blind-spots" },
    { file: "photo/без камер/2 (23).jpeg", label_ru: "Без камер #73", label_kz: "Камерасыз #73", category: "blind-spots" },
    { file: "photo/без камер/2 (24).jpeg", label_ru: "Без камер #74", label_kz: "Камерасыз #74", category: "blind-spots" },
    { file: "photo/без камер/2 (25).jpeg", label_ru: "Без камер #75", label_kz: "Камерасыз #75", category: "blind-spots" },
    { file: "photo/без камер/2 (26).jpeg", label_ru: "Без камер #76", label_kz: "Камерасыз #76", category: "blind-spots" },
    { file: "photo/без камер/2 (27).jpeg", label_ru: "Без камер #77", label_kz: "Камерасыз #77", category: "blind-spots" },
    { file: "photo/без камер/2 (28).jpeg", label_ru: "Без камер #78", label_kz: "Камерасыз #78", category: "blind-spots" },
    { file: "photo/без камер/2 (29).jpeg", label_ru: "Без камер #79", label_kz: "Камерасыз #79", category: "blind-spots" },
    { file: "photo/без камер/2 (30).jpeg", label_ru: "Без камер #80", label_kz: "Камерасыз #80", category: "blind-spots" },
    { file: "photo/без камер/2 (31).jpeg", label_ru: "Без камер #81", label_kz: "Камерасыз #81", category: "blind-spots" },
    { file: "photo/без камер/2 (32).jpeg", label_ru: "Без камер #82", label_kz: "Камерасыз #82", category: "blind-spots" },
    { file: "photo/без камер/2 (33).jpeg", label_ru: "Без камер #83", label_kz: "Камерасыз #83", category: "blind-spots" },
    { file: "photo/без камер/2 (34).jpeg", label_ru: "Без камер #84", label_kz: "Камерасыз #84", category: "blind-spots" },
    { file: "photo/без камер/2 (35).jpeg", label_ru: "Без камер #85", label_kz: "Камерасыз #85", category: "blind-spots" },
    { file: "photo/без камер/2 (36).jpeg", label_ru: "Без камер #86", label_kz: "Камерасыз #86", category: "blind-spots" },
    { file: "photo/без камер/2 (37).jpeg", label_ru: "Без камер #87", label_kz: "Камерасыз #87", category: "blind-spots" },
    { file: "photo/без камер/2 (38).jpeg", label_ru: "Без камер #88", label_kz: "Камерасыз #88", category: "blind-spots" },
    { file: "photo/без камер/2 (39).jpeg", label_ru: "Без камер #89", label_kz: "Камерасыз #89", category: "blind-spots" },
    { file: "photo/без камер/2 (40).jpeg", label_ru: "Без камер #90", label_kz: "Камерасыз #90", category: "blind-spots" },
    { file: "photo/без камер/2 (41).jpeg", label_ru: "Без камер #91", label_kz: "Камерасыз #91", category: "blind-spots" },
    { file: "photo/без камер/2 (42).jpeg", label_ru: "Без камер #92", label_kz: "Камерасыз #92", category: "blind-spots" },
    { file: "photo/без камер/2 (43).jpeg", label_ru: "Без камер #93", label_kz: "Камерасыз #93", category: "blind-spots" },
    { file: "photo/без камер/2 (44).jpeg", label_ru: "Без камер #94", label_kz: "Камерасыз #94", category: "blind-spots" },
    { file: "photo/без камер/2 (45).jpeg", label_ru: "Без камер #95", label_kz: "Камерасыз #95", category: "blind-spots" },
    { file: "photo/без камер/2 (46).jpeg", label_ru: "Без камер #96", label_kz: "Камерасыз #96", category: "blind-spots" },
    { file: "photo/без камер/2 (47).jpeg", label_ru: "Без камер #97", label_kz: "Камерасыз #97", category: "blind-spots" },
    { file: "photo/без камер/2 (48).jpeg", label_ru: "Без камер #98", label_kz: "Камерасыз #98", category: "blind-spots" },
    { file: "photo/без камер/3 (1).jpeg", label_ru: "Без камер #99", label_kz: "Камерасыз #99", category: "blind-spots" },
    { file: "photo/без камер/3 (2).jpeg", label_ru: "Без камер #100", label_kz: "Камерасыз #100", category: "blind-spots" },
    { file: "photo/без камер/3 (3).jpeg", label_ru: "Без камер #101", label_kz: "Камерасыз #101", category: "blind-spots" },
    { file: "photo/без камер/3 (4).jpeg", label_ru: "Без камер #102", label_kz: "Камерасыз #102", category: "blind-spots" },
    { file: "photo/без камер/3 (5).jpeg", label_ru: "Без камер #103", label_kz: "Камерасыз #103", category: "blind-spots" },
    { file: "photo/без камер/3 (6).jpeg", label_ru: "Без камер #104", label_kz: "Камерасыз #104", category: "blind-spots" },
    { file: "photo/без камер/3 (7).jpeg", label_ru: "Без камер #105", label_kz: "Камерасыз #105", category: "blind-spots" },
    { file: "photo/без камер/3 (8).jpeg", label_ru: "Без камер #106", label_kz: "Камерасыз #106", category: "blind-spots" },
    { file: "photo/без камер/3 (9).jpeg", label_ru: "Без камер #107", label_kz: "Камерасыз #107", category: "blind-spots" },
    { file: "photo/без камер/3 (10).jpeg", label_ru: "Без камер #108", label_kz: "Камерасыз #108", category: "blind-spots" },
    { file: "photo/без камер/3 (11).jpeg", label_ru: "Без камер #109", label_kz: "Камерасыз #109", category: "blind-spots" },
    { file: "photo/без камер/3 (12).jpeg", label_ru: "Без камер #110", label_kz: "Камерасыз #110", category: "blind-spots" },
    { file: "photo/без камер/3 (13).jpeg", label_ru: "Без камер #111", label_kz: "Камерасыз #111", category: "blind-spots" },
    { file: "photo/без камер/3 (14).jpeg", label_ru: "Без камер #112", label_kz: "Камерасыз #112", category: "blind-spots" },
    { file: "photo/без камер/3 (15).jpeg", label_ru: "Без камер #113", label_kz: "Камерасыз #113", category: "blind-spots" },
    { file: "photo/без камер/3 (16).jpeg", label_ru: "Без камер #114", label_kz: "Камерасыз #114", category: "blind-spots" },
    { file: "photo/без камер/3 (17).jpeg", label_ru: "Без камер #115", label_kz: "Камерасыз #115", category: "blind-spots" },
    { file: "photo/без камер/3 (18).jpeg", label_ru: "Без камер #116", label_kz: "Камерасыз #116", category: "blind-spots" },
    { file: "photo/без камер/3 (19).jpeg", label_ru: "Без камер #117", label_kz: "Камерасыз #117", category: "blind-spots" },
    { file: "photo/без камер/3 (20).jpeg", label_ru: "Без камер #118", label_kz: "Камерасыз #118", category: "blind-spots" },
    { file: "photo/без камер/3 (21).jpeg", label_ru: "Без камер #119", label_kz: "Камерасыз #119", category: "blind-spots" },
    { file: "photo/без камер/3 (22).jpeg", label_ru: "Без камер #120", label_kz: "Камерасыз #120", category: "blind-spots" },
    { file: "photo/без камер/3 (23).jpeg", label_ru: "Без камер #121", label_kz: "Камерасыз #121", category: "blind-spots" },
    { file: "photo/без камер/3 (24).jpeg", label_ru: "Без камер #122", label_kz: "Камерасыз #122", category: "blind-spots" },
    { file: "photo/без камер/3 (25).jpeg", label_ru: "Без камер #123", label_kz: "Камерасыз #123", category: "blind-spots" },
    { file: "photo/без камер/3 (26).jpeg", label_ru: "Без камер #124", label_kz: "Камерасыз #124", category: "blind-spots" },
    { file: "photo/без камер/3 (27).jpeg", label_ru: "Без камер #125", label_kz: "Камерасыз #125", category: "blind-spots" },
    { file: "photo/без камер/3 (28).jpeg", label_ru: "Без камер #126", label_kz: "Камерасыз #126", category: "blind-spots" },
    { file: "photo/без камер/3 (29).jpeg", label_ru: "Без камер #127", label_kz: "Камерасыз #127", category: "blind-spots" },
    { file: "photo/без камер/3 (30).jpeg", label_ru: "Без камер #128", label_kz: "Камерасыз #128", category: "blind-spots" },
    { file: "photo/без камер/3 (31).jpeg", label_ru: "Без камер #129", label_kz: "Камерасыз #129", category: "blind-spots" },
    { file: "photo/без камер/3 (32).jpeg", label_ru: "Без камер #130", label_kz: "Камерасыз #130", category: "blind-spots" },
    { file: "photo/без камер/3 (33).jpeg", label_ru: "Без камер #131", label_kz: "Камерасыз #131", category: "blind-spots" },
    { file: "photo/без камер/3 (34).jpeg", label_ru: "Без камер #132", label_kz: "Камерасыз #132", category: "blind-spots" },
    { file: "photo/без камер/3 (35).jpeg", label_ru: "Без камер #133", label_kz: "Камерасыз #133", category: "blind-spots" },

    // Без света
    { file: "photo/без света/image1.jpeg", label_ru: "Без света #1", label_kz: "Жарықсыз #1", category: "unlit" },
    { file: "photo/без света/image2.jpeg", label_ru: "Без света #2", label_kz: "Жарықсыз #2", category: "unlit" },
    { file: "photo/без света/image3.jpeg", label_ru: "Без света #3", label_kz: "Жарықсыз #3", category: "unlit" },
    { file: "photo/без света/image4.jpeg", label_ru: "Без света #4", label_kz: "Жарықсыз #4", category: "unlit" },
    { file: "photo/без света/image5.jpeg", label_ru: "Без света #5", label_kz: "Жарықсыз #5", category: "unlit" },
    { file: "photo/без света/image6.jpeg", label_ru: "Без света #6", label_kz: "Жарықсыз #6", category: "unlit" },
    { file: "photo/без света/image7.jpeg", label_ru: "Без света #7", label_kz: "Жарықсыз #7", category: "unlit" },
    { file: "photo/без света/image8.jpeg", label_ru: "Без света #8", label_kz: "Жарықсыз #8", category: "unlit" },
    { file: "photo/без света/image9.jpeg", label_ru: "Без света #9", label_kz: "Жарықсыз #9", category: "unlit" },
    { file: "photo/без света/image10.jpeg", label_ru: "Без света #10", label_kz: "Жарықсыз #10", category: "unlit" },
    { file: "photo/без света/image11.jpeg", label_ru: "Без света #11", label_kz: "Жарықсыз #11", category: "unlit" },
    { file: "photo/без света/image12.jpeg", label_ru: "Без света #12", label_kz: "Жарықсыз #12", category: "unlit" },
    { file: "photo/без света/image13.jpeg", label_ru: "Без света #13", label_kz: "Жарықсыз #13", category: "unlit" },
    { file: "photo/без света/image14.jpeg", label_ru: "Без света #14", label_kz: "Жарықсыз #14", category: "unlit" },
    { file: "photo/без света/image15.jpeg", label_ru: "Без света #15", label_kz: "Жарықсыз #15", category: "unlit" },
    { file: "photo/без света/image16.jpeg", label_ru: "Без света #16", label_kz: "Жарықсыз #16", category: "unlit" },
    { file: "photo/без света/image17.jpeg", label_ru: "Без света #17", label_kz: "Жарықсыз #17", category: "unlit" },
    { file: "photo/без света/image18.jpeg", label_ru: "Без света #18", label_kz: "Жарықсыз #18", category: "unlit" },
    { file: "photo/без света/image19.jpeg", label_ru: "Без света #19", label_kz: "Жарықсыз #19", category: "unlit" },
    { file: "photo/без света/image20.jpeg", label_ru: "Без света #20", label_kz: "Жарықсыз #20", category: "unlit" },
    { file: "photo/без света/image21.jpeg", label_ru: "Без света #21", label_kz: "Жарықсыз #21", category: "unlit" },
    { file: "photo/без света/image22.jpeg", label_ru: "Без света #22", label_kz: "Жарықсыз #22", category: "unlit" },
    { file: "photo/без света/image23.jpeg", label_ru: "Без света #23", label_kz: "Жарықсыз #23", category: "unlit" },

    // Заброшенные здания
    { file: "photo/заброшенные здания/image1.jpeg", label_ru: "Заброшенное здание #1", label_kz: "Тастанды ғимарат #1", category: "abandoned" },
    { file: "photo/заброшенные здания/image2.jpeg", label_ru: "Заброшенное здание #2", label_kz: "Тастанды ғимарат #2", category: "abandoned" },
    { file: "photo/заброшенные здания/image3.jpeg", label_ru: "Заброшенное здание #3", label_kz: "Тастанды ғимарат #3", category: "abandoned" },
    { file: "photo/заброшенные здания/image4.jpeg", label_ru: "Заброшенное здание #4", label_kz: "Тастанды ғимарат #4", category: "abandoned" },
    { file: "photo/заброшенные здания/image5.jpeg", label_ru: "Заброшенное здание #5", label_kz: "Тастанды ғимарат #5", category: "abandoned" },
    { file: "photo/заброшенные здания/image6.jpeg", label_ru: "Заброшенное здание #6", label_kz: "Тастанды ғимарат #6", category: "abandoned" },
    { file: "photo/заброшенные здания/image7.jpeg", label_ru: "Заброшенное здание #7", label_kz: "Тастанды ғимарат #7", category: "abandoned" },
    { file: "photo/заброшенные здания/image8.jpeg", label_ru: "Заброшенное здание #8", label_kz: "Тастанды ғимарат #8", category: "abandoned" },
    { file: "photo/заброшенные здания/image9.jpeg", label_ru: "Заброшенное здание #9", label_kz: "Тастанды ғимарат #9", category: "abandoned" },
    { file: "photo/заброшенные здания/image10.jpeg", label_ru: "Заброшенное здание #10", label_kz: "Тастанды ғимарат #10", category: "abandoned" },
    { file: "photo/заброшенные здания/image11.jpeg", label_ru: "Заброшенное здание #11", label_kz: "Тастанды ғимарат #11", category: "abandoned" },
    { file: "photo/заброшенные здания/image12.jpeg", label_ru: "Заброшенное здание #12", label_kz: "Тастанды ғимарат #12", category: "abandoned" },
    { file: "photo/заброшенные здания/image13.jpeg", label_ru: "Заброшенное здание #13", label_kz: "Тастанды ғимарат #13", category: "abandoned" },
    { file: "photo/заброшенные здания/image14.jpeg", label_ru: "Заброшенное здание #14", label_kz: "Тастанды ғимарат #14", category: "abandoned" },
    { file: "photo/заброшенные здания/image15.jpeg", label_ru: "Заброшенное здание #15", label_kz: "Тастанды ғимарат #15", category: "abandoned" },
    { file: "photo/заброшенные здания/image16.jpeg", label_ru: "Заброшенное здание #16", label_kz: "Тастанды ғимарат #16", category: "abandoned" },
    { file: "photo/заброшенные здания/image17.jpeg", label_ru: "Заброшенное здание #17", label_kz: "Тастанды ғимарат #17", category: "abandoned" },
    { file: "photo/заброшенные здания/image18.jpeg", label_ru: "Заброшенное здание #18", label_kz: "Тастанды ғимарат #18", category: "abandoned" },
    { file: "photo/заброшенные здания/image19.jpeg", label_ru: "Заброшенное здание #19", label_kz: "Тастанды ғимарат #19", category: "abandoned" },
    { file: "photo/заброшенные здания/image20.jpeg", label_ru: "Заброшенное здание #20", label_kz: "Тастанды ғимарат #20", category: "abandoned" },
    { file: "photo/заброшенные здания/image21.jpeg", label_ru: "Заброшенное здание #21", label_kz: "Тастанды ғимарат #21", category: "abandoned" },
    { file: "photo/заброшенные здания/image22.jpeg", label_ru: "Заброшенное здание #22", label_kz: "Тастанды ғимарат #22", category: "abandoned" },
    { file: "photo/заброшенные здания/image23.jpeg", label_ru: "Заброшенное здание #23", label_kz: "Тастанды ғимарат #23", category: "abandoned" },
    { file: "photo/заброшенные здания/image24.jpeg", label_ru: "Заброшенное здание #24", label_kz: "Тастанды ғимарат #24", category: "abandoned" },
    { file: "photo/заброшенные здания/image25.jpeg", label_ru: "Заброшенное здание #25", label_kz: "Тастанды ғимарат #25", category: "abandoned" },
    { file: "photo/заброшенные здания/image26.jpeg", label_ru: "Заброшенное здание #26", label_kz: "Тастанды ғимарат #26", category: "abandoned" },
    { file: "photo/заброшенные здания/image27.jpeg", label_ru: "Заброшенное здание #27", label_kz: "Тастанды ғимарат #27", category: "abandoned" },
    { file: "photo/заброшенные здания/image28.jpeg", label_ru: "Заброшенное здание #28", label_kz: "Тастанды ғимарат #28", category: "abandoned" },
    { file: "photo/заброшенные здания/image29.jpeg", label_ru: "Заброшенное здание #29", label_kz: "Тастанды ғимарат #29", category: "abandoned" },
    { file: "photo/заброшенные здания/image30.jpeg", label_ru: "Заброшенное здание #30", label_kz: "Тастанды ғимарат #30", category: "abandoned" },
    { file: "photo/заброшенные здания/image31.jpeg", label_ru: "Заброшенное здание #31", label_kz: "Тастанды ғимарат #31", category: "abandoned" },
    { file: "photo/заброшенные здания/image32.jpeg", label_ru: "Заброшенное здание #32", label_kz: "Тастанды ғимарат #32", category: "abandoned" },
    { file: "photo/заброшенные здания/image33.jpeg", label_ru: "Заброшенное здание #33", label_kz: "Тастанды ғимарат #33", category: "abandoned" },
    { file: "photo/заброшенные здания/image34.jpeg", label_ru: "Заброшенное здание #34", label_kz: "Тастанды ғимарат #34", category: "abandoned" },
    { file: "photo/заброшенные здания/image35.jpeg", label_ru: "Заброшенное здание #35", label_kz: "Тастанды ғимарат #35", category: "abandoned" },
    { file: "photo/заброшенные здания/image36.jpeg", label_ru: "Заброшенное здание #36", label_kz: "Тастанды ғимарат #36", category: "abandoned" },
    { file: "photo/заброшенные здания/image37.jpeg", label_ru: "Заброшенное здание #37", label_kz: "Тастанды ғимарат #37", category: "abandoned" },
    { file: "photo/заброшенные здания/image38.jpeg", label_ru: "Заброшенное здание #38", label_kz: "Тастанды ғимарат #38", category: "abandoned" },
    { file: "photo/заброшенные здания/image39.jpeg", label_ru: "Заброшенное здание #39", label_kz: "Тастанды ғимарат #39", category: "abandoned" },
    { file: "photo/заброшенные здания/image40.jpeg", label_ru: "Заброшенное здание #40", label_kz: "Тастанды ғимарат #40", category: "abandoned" },
    { file: "photo/заброшенные здания/image41.jpeg", label_ru: "Заброшенное здание #41", label_kz: "Тастанды ғимарат #41", category: "abandoned" },
    { file: "photo/заброшенные здания/image42.jpeg", label_ru: "Заброшенное здание #42", label_kz: "Тастанды ғимарат #42", category: "abandoned" },
    { file: "photo/заброшенные здания/image43.jpeg", label_ru: "Заброшенное здание #43", label_kz: "Тастанды ғимарат #43", category: "abandoned" }

];
